### ISSUE TITLE
Error uploading firmware: JArduino does not name a type

### ISSUE THREAD

**Issue by carloVentrella** [SINTEF-9012/JArduino#29]
I'm trying to upload the firmware but I get always an error.
First time it told me "WConstants.h: no such file or directory", now I re-downloaded all the library and the error is this: 

<code>
JArduinoFirmware:21: error: 'JArduino' does not name a type
JArduinoFirmware.pde: In function 'void interrupt0()':
JArduinoFirmware:24: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void interrupt1()':
JArduinoFirmware:28: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void receivedigitalRead(uint8_t)':
JArduinoFirmware:36: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void receiveanalogRead(uint8_t)':
JArduinoFirmware:46: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void receiveping()':
JArduinoFirmware:52: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void receiveeeprom_read(uint16_t)':
JArduinoFirmware:70: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void receiveeeprom_sync_write(uint16_t, uint8_t)':
JArduinoFirmware:74: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void setup()':
JArduinoFirmware:83: error: '_JArduino' was not declared in this scope
JArduinoFirmware.pde: In function 'void loop()':
JArduinoFirmware:89: error: '_JArduino' was not declared in this scope
</code>

I can't understand what's wrong..

**Comment by skizilarslan** [comment]
I also have same problem. I'm using Arduino IDE 1.0.6 and I replaced the WProgram.h by Arduino.h but it doesnt work. I downloaded Arduino IDE 0022 (thought may the old version can work on it) but still getting same error. What am I doing wrong ?

**Comment by tsarnow** [comment]
@skizilarslan have you changed the JArduino.cpp, too?

**Comment by skizilarslan** [comment]
How many files that I have to change? WProgram.h is already in Jarduino.cpp
so i changed it. What is the other file?
20 May 2015 09:25 tarihinde "tsarnow" <notifications@github.com> yazdı:

**Comment by tsarnow** [comment]
As I remember I just changed one file maybe try a full text search :)

**Comment by brice-morin** [comment]
[The latest release](https://github.com/SINTEF-9012/JArduino/releases/tag/0.1.7b) should hopefully solve these problems
