### ISSUE TITLE
Modernize JArduino

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/JArduino#30]
We should make sure JArduino runs on the latest version of the Arduino IDE and nodes. See Issue #29 and #28, which can probably be solved by this modernization.

**Comment by gbakus** [comment]
So for time beeing  while awaiting for fix here is how I made JArduino work on ubuntu 14:04 .
1. Download version 0023 from http://arduino.cc/en/Main/OldSoftwareReleases
2. Remove any previuos versions of  gcc-avr avr-libc in terminal type
      sudo apt-get purge gcc-avr 
      sudo apt-get purge avr-libc
3. Download old versions of packaged below from 
       http://ftp.de.debian.org/debian/pool/main/a/avr-libc/avr-libc_1.6.8-2_all.deb
        here is package deetails and versions: https://packages.debian.org/squeeze/all/avr-libc
4. Go to download diectory and install package by typing 
     sudo dpkg  -i  avr-libc_1.6.8-2_all.deb
     If this shows conflict and errors type:
     sudo dpkg  --force-all  -i  avr-libc_1.6.8-2_all.deb
5. Srat Ardiuno IDE and run examples
!!!! Do this at your own risk preferably in separate Ubuntu installiation !!!
