### ISSUE TITLE
Half of the output tension

### ISSUE THREAD

**Issue by bahiald** [SINTEF-9012/JArduino#44]
When I run the blink example I get 2.5V output, but when I run the Arduino blink (not using JArduino) I get 5V output.

I tried using IDE versions 1.0 and 1.6.7

**Comment by brice-morin** [comment]
Hi,

It might be that the pin is not properly set in output mode (maybe serial was not completely ready and command was lost). Can you try to update the blink so that you always set the pin in output mode before blinking it?
