### ISSUE TITLE
initialize jArduino in firmware with specific baud - not supported

### ISSUE THREAD

**Issue by lobsteroh** [SINTEF-9012/JArduino#56]
recommendation for supporting higher baud rate in firmware is via ...

    void setup() {
	_JArduino.init_JArduino(115200);
    }

unfortunately uploading this to arduino produces with compile from source gives ...

    exit status 1
    no matching function for call to 'JArduino::init_JArduino(long int)'

**Comment by brice-morin** [comment]
OK, I guess we should change the signature of [that method](https://github.com/SINTEF-9012/JArduino/blob/master/jarduino.core/src/main/arduino/JArduino/JArduino.cpp#L36) so that it can take a long int as parameter

**Comment by lobsteroh** [comment]
yeah, i have been playing in changing the .h and .cpp files for having both constructors. in header ...

    	void init_JArduino();
 	void init_JArduino(uint16_t baud);

and .cpp

    // Public Methods //////////////////////////////////////////////////////////////
    void JArduino::init_JArduino(uint16_t baud = 9600) {
	// init the serial port
	Serial.begin(baud);
    }

    void JArduino::init_JArduino(void) {
	// init the serial port
	init_JArduino(9600);
    }

but upload of the new firmware to arduino fails ... what am i missing?

**Comment by lobsteroh** [comment]
ok, in the firmware i try ...

    void setup() {
	uint16_t baud = 9600;
        _JArduino.init_JArduino(baud);
    }

and that works, but how to pass in the baud rate from jArduino?
