### ISSUE TITLE
library is not yet complete for android serial communication

### ISSUE THREAD

**Issue by meedeepak** [SINTEF-9012/JArduino#71]
I like the library and the way it uses arduino but please make android serial communication example

**Comment by meedeepak** [comment]
After working literally for 48 hrs i finally made this work
https://github.com/meedeepak/Arduino-android-serial-communication

**Comment by brice-morin** [comment]
Excellent! Not sure we would have spent less than 48 hours implementing that cool feature. If you want, you can submit a pull request.
