### ISSUE TITLE
JArduino Firmware error

### ISSUE THREAD

**Issue by tsatatwer** [SINTEF-9012/JArduino#84]
Hi ,
I got this error while try to upload JArduino firmware:
C:\Program Files (x86)\Arduino\libraries\JArduino\JArduino.cpp:38:15: error: 'baud' was not declared in this scope

  Serial.begin(baud);

**Comment by mmihuu** [comment]
Hello
I`m currently struggling with this issue. Have you managed to sort it out? Thanks in advance for any help.
Cheers
