### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Munoon** [SINTEF-9012/JArduino#85]
Hi! Trying to install your JArduino firmware on my Arduino UNO and have compilation problem in Arduino's program.
![image](https://user-images.githubusercontent.com/43534008/61823524-a5045d00-ae64-11e9-8d9f-0bebbde4bd35.png)
Most of messages in russion, but the main point is that Arduino's program can't compile your code for Arduino UNO.

Sorry for my bad english.

**Comment by brice-morin** [comment]
I guess the easiest fix would be to manually edit [this line](https://github.com/SINTEF-9012/JArduino/blob/master/jarduino.core/src/main/arduino/JArduino/JArduino.cpp#L38) and replace `baud` by `9600`.

**Comment by Munoon** [comment]
Yes, that works. Thank you!
